const runesData = [
  { id: "fehu", symbol: "ᚠ", name: "Fehu", meaning: "財富", bgClass: "bg-surface-container-lowest" },
  { id: "uruz", symbol: "ᚢ", name: "Uruz", meaning: "蠻牛", bgClass: "bg-surface-container-lowest" },
  { id: "thurisaz", symbol: "ᚦ", name: "Thurisaz", meaning: "雷神槌", bgClass: "bg-surface-container-low" },
  { id: "ansuz", symbol: "ᚨ", name: "Ansuz", meaning: "智慧", bgClass: "bg-surface-container-lowest" },
  { id: "raido", symbol: "ᚱ", name: "Raido", meaning: "旅人", bgClass: "bg-surface-container-lowest" },
  { id: "kenaz", symbol: "ᚲ", name: "Kenaz", meaning: "火炬", bgClass: "bg-surface-container-low" },
  { id: "gebo", symbol: "ᚷ", name: "Gebo", meaning: "禮物", bgClass: "bg-surface-container-lowest" },
  { id: "wunjo", symbol: "ᚹ", name: "Wunjo", meaning: "喜悅", bgClass: "bg-surface-container-lowest" },
  { id: "hagalaz", symbol: "ᚺ", name: "Hagalaz", meaning: "風暴", bgClass: "bg-surface-container-low" },
  { id: "nauthiz", symbol: "ᚾ", name: "Nauthiz", meaning: "末籤（生存）", bgClass: "bg-surface-container-lowest" },
  { id: "isa", symbol: "ᛁ", name: "Isa", meaning: "冰", bgClass: "bg-surface-container-lowest" },
  { id: "jera", symbol: "ᛃ", name: "Jera", meaning: "豐收", bgClass: "bg-surface-container-low" },
  { id: "eihwaz", symbol: "ᛇ", name: "Eihwaz", meaning: "紫衫", bgClass: "bg-surface-container-lowest" },
  { id: "perthro", symbol: "ᛈ", name: "Perthro", meaning: "骰杯", bgClass: "bg-surface-container-lowest" },
  { id: "algiz", symbol: "ᛉ", name: "Algiz", meaning: "保護", bgClass: "bg-surface-container-low" },
  { id: "sowilo", symbol: "ᛋ", name: "Sowilo", meaning: "太陽", bgClass: "bg-surface-container-lowest" },
  { id: "tiwaz", symbol: "ᛏ", name: "Tiwaz", meaning: "戰神", bgClass: "bg-surface-container-lowest" },
  { id: "berkana", symbol: "ᛒ", name: "Berkana", meaning: "樺樹", bgClass: "bg-surface-container-low" },
  { id: "ehwaz", symbol: "ᛖ", name: "Ehwaz", meaning: "駿馬", bgClass: "bg-surface-container-lowest" },
  { id: "mannaz", symbol: "ᛗ", name: "Mannaz", meaning: "人類", bgClass: "bg-surface-container-lowest" },
  { id: "laguz", symbol: "ᛚ", name: "Laguz", meaning: "湖水", bgClass: "bg-surface-container-low" },
  { id: "inguz", symbol: "ᛝ", name: "Inguz", meaning: "種子", bgClass: "bg-surface-container-lowest" },
  { id: "dagaz", symbol: "ᛞ", name: "Dagaz", meaning: "黎明", bgClass: "bg-surface-container-lowest" },
  { id: "othala", symbol: "ᛟ", name: "Othala", meaning: "家庭", bgClass: "bg-surface-container-low" },
  { id: "wyrd", symbol: " ", name: "Wyrd", meaning: "籤王（空白符文）", bgClass: "bg-surface-container-lowest" }
];
