const runesData = [
  { id: "fehu", symbol: "ᚠ", name: "Fehu", meaning: "財富", bgClass: "bg-surface-container-lowest" },
  { id: "uruz", symbol: "ᚢ", name: "Uruz", meaning: "力量", bgClass: "bg-surface-container-lowest" },
  { id: "thurisaz", symbol: "ᚦ", name: "Thurisaz", meaning: "巨人", bgClass: "bg-surface-container-low" },
  { id: "ansuz", symbol: "ᚨ", name: "Ansuz", meaning: "智慧", bgClass: "bg-surface-container-lowest" },
  { id: "raidho", symbol: "ᚱ", name: "Raidho", meaning: "旅程", bgClass: "bg-surface-container-lowest" },
  { id: "kenaz", symbol: "ᚲ", name: "Kenaz", meaning: "火炬", bgClass: "bg-surface-container-low" },
  { id: "gebo", symbol: "ᚷ", name: "Gebo", meaning: "禮物", bgClass: "bg-surface-container-lowest" },
  { id: "wunjo", symbol: "ᚹ", name: "Wunjo", meaning: "喜悅", bgClass: "bg-surface-container-lowest" },
  { id: "hagalaz", symbol: "ᚺ", name: "Hagalaz", meaning: "冰雹", bgClass: "bg-surface-container-low" },
  { id: "nauthiz", symbol: "ᚾ", name: "Nauthiz", meaning: "匱乏", bgClass: "bg-surface-container-lowest" },
  { id: "isa", symbol: "ᛁ", name: "Isa", meaning: "寒冰", bgClass: "bg-surface-container-lowest" },
  { id: "jera", symbol: "ᛃ", name: "Jera", meaning: "豐收", bgClass: "bg-surface-container-low" },
  { id: "eihwaz", symbol: "ᛇ", name: "Eihwaz", meaning: "紫衫", bgClass: "bg-surface-container-lowest" },
  { id: "perthro", symbol: "ᛈ", name: "Perthro", meaning: "命運", bgClass: "bg-surface-container-lowest" },
  { id: "algiz", symbol: "ᛉ", name: "Algiz", meaning: "保護", bgClass: "bg-surface-container-low" },
  { id: "sowilo", symbol: "ᛊ", name: "Sowilo", meaning: "太陽", bgClass: "bg-surface-container-lowest" },
  { id: "tiwaz", symbol: "ᛏ", name: "Tiwaz", meaning: "正義", bgClass: "bg-surface-container-lowest" },
  { id: "berkano", symbol: "ᛒ", name: "Berkano", meaning: "孕育", bgClass: "bg-surface-container-low" },
  { id: "ehwaz", symbol: "ᛖ", name: "Ehwaz", meaning: "靈馬", bgClass: "bg-surface-container-lowest" },
  { id: "mannaz", symbol: "ᛗ", name: "Mannaz", meaning: "人類", bgClass: "bg-surface-container-lowest" },
  { id: "laguz", symbol: "ᛚ", name: "Laguz", meaning: "流水", bgClass: "bg-surface-container-low" },
  { id: "ingwaz", symbol: "ᛜ", name: "Ingwaz", meaning: "潛能", bgClass: "bg-surface-container-lowest" },
  { id: "dagaz", symbol: "ᛞ", name: "Dagaz", meaning: "黎明", bgClass: "bg-surface-container-lowest" },
  { id: "othala", symbol: "ᛟ", name: "Othala", meaning: "傳承", bgClass: "bg-surface-container-low" },
  { id: "wyrd", symbol: "", name: "Wyrd", meaning: "空之符", bgClass: "bg-surface-container-lowest" }
];
