tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "surface-container-highest": "#f0e1c7",
                "surface-bright": "#fff8f2",
                "outline": "#877366",
                "inverse-primary": "#ffb781",
                "outline-variant": "#dac2b3",
                "tertiary-fixed-dim": "#e3beb8",
                "on-secondary-fixed-variant": "#4a473d",
                "surface": "#fff8f2",
                "on-primary": "#ffffff",
                "on-primary-fixed-variant": "#703800",
                "primary-fixed": "#ffdcc5",
                "on-primary-container": "#fffbff",
                "secondary-fixed-dim": "#ccc6b9",
                "surface-container-low": "#fff2dd",
                "surface-variant": "#f0e1c7",
                "on-secondary": "#ffffff",
                "secondary-container": "#e8e2d4",
                "on-tertiary-fixed": "#2b1613",
                "on-primary-fixed": "#301400",
                "on-tertiary-container": "#fffbff",
                "tertiary": "#725550",
                "surface-container-lowest": "#ffffff",
                "tertiary-container": "#8c6d68",
                "error": "#ba1a1a",
                "on-error": "#ffffff",
                "surface-tint": "#934b00",
                "primary": "#8f4900",
                "on-tertiary": "#ffffff",
                "error-container": "#ffdad6",
                "surface-container": "#fbecd2",
                "on-surface-variant": "#544338",
                "primary-fixed-dim": "#ffb781",
                "primary-container": "#af6018",
                "secondary": "#625e54",
                "on-surface": "#221b0b",
                "surface-container-high": "#f6e6cc",
                "on-tertiary-fixed-variant": "#5b403c",
                "on-error-container": "#93000a",
                "secondary-fixed": "#e8e2d4",
                "tertiary-fixed": "#ffdad4",
                "background": "#fff8f2",
                "surface-dim": "#e7d8bf",
                "on-background": "#221b0b",
                "inverse-on-surface": "#feefd5",
                "on-secondary-fixed": "#1e1c13",
                "inverse-surface": "#382f1e",
                "on-secondary-container": "#686459"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "fontFamily": {
                "headline": ["Newsreader", "Noto Serif", "serif"],
                "body": ["Noto Serif", "serif"],
                "label": ["Noto Serif", "serif"]
            }
        },
    },
}
